# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.FloatField()),
                ('observation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cnp', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('cellphone', models.CharField(max_length=50)),
                ('enrollment_Date', models.DateField()),
                ('rating', models.FloatField()),
                ('cache_professional_score', models.FloatField()),
                ('line_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=50)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks_Required_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.CharField(max_length=500)),
                ('min_score', models.FloatField()),
                ('number_of_persons', models.IntegerField()),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Skills')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks_Team_Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=500)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.FloatField()),
                ('observations', models.CharField(max_length=500)),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Skills')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('specific', models.CharField(max_length=50)),
                ('base_location', models.CharField(max_length=50)),
                ('leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Employees')),
            ],
        ),
        migrations.AddField(
            model_name='team_skill',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Teams'),
        ),
        migrations.AddField(
            model_name='team_assignments',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Teams'),
        ),
        migrations.AddField(
            model_name='tasks_team_assignments',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Teams'),
        ),
        migrations.AddField(
            model_name='employee_skills',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Employees'),
        ),
        migrations.AddField(
            model_name='employee_skills',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Skills'),
        ),
        migrations.AddField(
            model_name='employee_roles',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Employees'),
        ),
        migrations.AddField(
            model_name='employee_roles',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Skills'),
        ),
    ]
