# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workish', '0002_auto_20180529_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='address',
            new_name='email',
        ),
        migrations.AddField(
            model_name='employees',
            name='username',
            field=models.CharField(default=b'nousername', max_length=50),
        ),
    ]
