# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workish', '0003_auto_20180530_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='cache_professional_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='enrollment_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
