# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-30 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workish', '0005_auto_20180530_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_roles',
            name='skill_id',
        ),
        migrations.AddField(
            model_name='employee_roles',
            name='role_id',
            field=models.ForeignKey(default=b'1000', on_delete=django.db.models.deletion.CASCADE, to='workish.Roles'),
        ),
    ]
