# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-30 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workish', '0006_auto_20180531_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
