# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-30 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workish', '0007_auto_20180531_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_roles',
            name='assignment_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee_roles',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
