# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-31 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workish', '0010_auto_20180531_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_roles',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workish.Roles'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='enrollment_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
