# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-31 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workish', '0011_auto_20180531_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='enrollment_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
